apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdep
spec:
  template:
    metadata:
      name: myweb
      labels:
        app: apache
    spec:
      containers:
        - name: ngx1
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      app: apache

